import { mutation } from "../_generated/server";

export const seedAgronomicPlans = mutation({
  args: {},
  handler: async (ctx) => {
    const planData = {
      planId: "HVPLAN-ZAF-L02-2026",
      lotCode: "zafiro-001",
      farmCode: "HV-HN-ZAF",
      farmName: "Finca Zafiro",
      variety: "Parainema",
      altitudeMsnm: 1300,
      areaManzanas: 1.0,
      areaHectares: 0.7,
      cycleYear: 2026,
      ticketUsd: 3425,
      totalCostAgronomic: 1450,
      totalCostIotService: 40,
      totalPlan: 1490,
      iotInfrastructureHarvverse: 6300,
      splitFarmer: 0.6,
      splitPartner: 0.4,
      platformCommission: 0.1,
      pricePerLbFixed: 3.5,
      priceFloor: 2.5,
      yieldY1Qq: 6,
      yieldY2Qq: 10,
      yieldY3Qq: 14,
      yieldCeilingQq: 22,
      phygitalCoffeeLb: 5,
      phygitalDelivery: "January 2027",
      profile: "C-Premium",
      validatorName: "Jorge Alberto Lanza",
      validatorTitle:
        "Cup of Excellence Honduras 2013 World Champion (92.75 pts), 30+ años producción",
      milestones: [
        {
          number: 1,
          name: "Diagnóstico & Línea Base",
          monthStart: 2,
          monthEnd: 2,
          cash: 25,
          marketplace: 85,
          total: 110,
          pct: 7.4,
        },
        {
          number: 2,
          name: "Preparación & Poda",
          monthStart: 3,
          monthEnd: 4,
          cash: 115,
          marketplace: 155,
          total: 270,
          pct: 18.1,
        },
        {
          number: 3,
          name: "Nutrición Base",
          monthStart: 4,
          monthEnd: 5,
          cash: 50,
          marketplace: 175,
          total: 225,
          pct: 15.1,
        },
        {
          number: 4,
          name: "Mantenimiento & Sanidad",
          monthStart: 6,
          monthEnd: 8,
          cash: 110,
          marketplace: 65,
          total: 175,
          pct: 11.7,
        },
        {
          number: 5,
          name: "Nutrición Refuerzo & Pre-cosecha",
          monthStart: 8,
          monthEnd: 9,
          cash: 40,
          marketplace: 170,
          total: 210,
          pct: 14.1,
        },
        {
          number: 6,
          name: "Cosecha & Beneficiado Premium",
          monthStart: 10,
          monthEnd: 12,
          cash: 355,
          marketplace: 105,
          total: 460,
          pct: 30.9,
        },
      ],
      activities: [
        {
          milestone: 1,
          code: "HARV-DIAG-SUELO",
          name: "Análisis de suelo",
          icon: "🧪",
          cash: 5,
          mkt: 25,
        },
        {
          milestone: 1,
          code: "HARV-DIAG-FITO",
          name: "Diagnóstico fitosanitario",
          icon: "🔬",
          cash: 5,
          mkt: 15,
        },
        {
          milestone: 1,
          code: "HARV-DIAG-GPS",
          name: "Mapeo GPS del lote",
          icon: "📍",
          cash: 5,
          mkt: 0,
        },
        {
          milestone: 1,
          code: "HARV-IOT-INSTALL",
          name: "Instalación sensores IoT",
          icon: "📡",
          cash: 10,
          mkt: 45,
        },
        {
          milestone: 2,
          code: "HARV-PODA-SELECT",
          name: "Poda selectiva rejuvenecimiento",
          icon: "✂️",
          cash: 45,
          mkt: 0,
        },
        {
          milestone: 2,
          code: "HARV-SOMBRA-REG",
          name: "Regulación de sombra",
          icon: "🌳",
          cash: 20,
          mkt: 0,
        },
        {
          milestone: 2,
          code: "HARV-FERT-CAL",
          name: "Encalado dolomítico",
          icon: "🎒",
          cash: 10,
          mkt: 85,
        },
        {
          milestone: 2,
          code: "HARV-MANT-CHAP1",
          name: "Primera chapea",
          icon: "🧹",
          cash: 25,
          mkt: 0,
        },
        {
          milestone: 2,
          code: "HARV-MANT-CALLE",
          name: "Limpieza de calles",
          icon: "🧹",
          cash: 15,
          mkt: 0,
        },
        {
          milestone: 2,
          code: "HARV-PREP-COMP",
          name: "Aplicación compost/bokashi",
          icon: "🌱",
          cash: 0,
          mkt: 70,
        },
        {
          milestone: 3,
          code: "HARV-FERT-DAP",
          name: "1ra fertilización 18-46-0",
          icon: "🎒",
          cash: 15,
          mkt: 75,
        },
        {
          milestone: 3,
          code: "HARV-FOLI-BORO",
          name: "Foliar de boro",
          icon: "💧",
          cash: 5,
          mkt: 20,
        },
        {
          milestone: 3,
          code: "HARV-FERT-UREA",
          name: "2da fertilización urea",
          icon: "🎒",
          cash: 15,
          mkt: 50,
        },
        {
          milestone: 3,
          code: "HARV-FERT-KCL",
          name: "Complemento KCl",
          icon: "🎒",
          cash: 15,
          mkt: 30,
        },
        {
          milestone: 4,
          code: "HARV-MANT-CHAP2",
          name: "Segunda chapea",
          icon: "🧹",
          cash: 25,
          mkt: 0,
        },
        {
          milestone: 4,
          code: "HARV-FUNG-COBRE",
          name: "Control preventivo roya (cobre)",
          icon: "🍄",
          cash: 15,
          mkt: 25,
        },
        {
          milestone: 4,
          code: "HARV-FUNG-SIST",
          name: "Fungicida sistémico",
          icon: "🍄",
          cash: 10,
          mkt: 20,
        },
        {
          milestone: 4,
          code: "HARV-PEST-TRAMPA",
          name: "Trampas Brocap para broca",
          icon: "🐛",
          cash: 10,
          mkt: 15,
        },
        {
          milestone: 4,
          code: "HARV-PEST-BIO",
          name: "Beauveria bassiana (biocontrol)",
          icon: "🐛",
          cash: 10,
          mkt: 5,
        },
        {
          milestone: 4,
          code: "HARV-IOT-MONIT",
          name: "Monitoreo IoT mensual",
          icon: "📡",
          cash: 0,
          mkt: 0,
        },
        {
          milestone: 4,
          code: "HARV-MANT-DRAIN",
          name: "Mantenimiento drenajes",
          icon: "🧹",
          cash: 40,
          mkt: 0,
        },
        {
          milestone: 5,
          code: "HARV-FERT-NPK3",
          name: "3ra fertilización 15-15-15",
          icon: "🎒",
          cash: 15,
          mkt: 75,
        },
        {
          milestone: 5,
          code: "HARV-FOLI-ZINC",
          name: "Foliar zinc",
          icon: "💧",
          cash: 5,
          mkt: 25,
        },
        {
          milestone: 5,
          code: "HARV-FOLI-CA",
          name: "Foliar calcio",
          icon: "💧",
          cash: 5,
          mkt: 25,
        },
        {
          milestone: 5,
          code: "HARV-FERT-MICRO",
          name: "Micronutrientes",
          icon: "🎒",
          cash: 5,
          mkt: 45,
        },
        {
          milestone: 5,
          code: "HARV-EVAL-MAD",
          name: "Evaluación maduración + plan cortes",
          icon: "☕",
          cash: 10,
          mkt: 0,
        },
        {
          milestone: 6,
          code: "HARV-COSE-CORTE1",
          name: "Primer corte selectivo",
          icon: "☕",
          cash: 100,
          mkt: 0,
        },
        {
          milestone: 6,
          code: "HARV-COSE-CORTE2",
          name: "Segundo corte selectivo",
          icon: "☕",
          cash: 100,
          mkt: 0,
        },
        {
          milestone: 6,
          code: "HARV-COSE-CORTE3",
          name: "Tercer corte selectivo",
          icon: "☕",
          cash: 80,
          mkt: 0,
        },
        {
          milestone: 6,
          code: "HARV-BENE-DESP",
          name: "Despulpado",
          icon: "📦",
          cash: 15,
          mkt: 15,
        },
        {
          milestone: 6,
          code: "HARV-BENE-FERM",
          name: "Fermentación controlada",
          icon: "📦",
          cash: 10,
          mkt: 20,
        },
        {
          milestone: 6,
          code: "HARV-BENE-LAVA",
          name: "Lavado",
          icon: "📦",
          cash: 10,
          mkt: 0,
        },
        {
          milestone: 6,
          code: "HARV-BENE-SECA",
          name: "Secado camas africanas",
          icon: "📦",
          cash: 25,
          mkt: 30,
        },
        {
          milestone: 6,
          code: "HARV-BENE-CUP",
          name: "Catación SCA profesional",
          icon: "🏆",
          cash: 5,
          mkt: 25,
        },
        {
          milestone: 6,
          code: "HARV-BENE-PREP",
          name: "Preparación muestra exportación",
          icon: "🏆",
          cash: 10,
          mkt: 15,
        },
      ],
      contractRules: {
        yieldCeiling: {
          y1: 8,
          y2: 14,
          y3: 18,
          absolute: 22,
        },
        yieldFloor: {
          normal: 6,
          forceMajeure: 4,
          severe: 2,
          catastrophe: 0,
        },
        priceFixed: 3.5,
        priceFloorRule: 2.5,
        upsideFormula: "60/40 on ALL profit, no separate excess formula, no cap",
      },
      createdAt: Date.now(),
    };

    let count = 0;
    const _id = await ctx.db.insert("agronomicPlans", planData);
    count++;

    return { success: true, agronomicPlansCreated: count, planId: _id };
  },
});
